apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrations
  namespace: cloud-ops
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: backend-migrations
    component: migrations
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: backend-migrations
        component: migrations
    spec:
      restartPolicy: Never

      initContainers:
        - name: wait-for-postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for PostgreSQL..."
              until pg_isready -h postgres -p 5432 -t 5; do
                echo "PostgreSQL not ready yet..."
                sleep 2
              done
              echo "PostgreSQL is ready."
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: migrations
          image: ghcr.io/dvdch1258/cloud-operations-backend:sha-dc94757
          imagePullPolicy: IfNotPresent
          command:
            - alembic
            - -c
            - /app/alembic.ini
            - upgrade
            - head
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
