apiVersion: v1
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: n8n
      group_by:
        - alertname
        - namespace
        - severity
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h

    inhibit_rules:
      - source_matchers:
          - alertname="BackendUnavailable"
        target_matchers:
          - alertname="BackendTargetDown"
        equal:
          - namespace

    receivers:
      - name: n8n
        webhook_configs:
          - url: http://172.22.0.1:5678/webhook/cloud-ops-technical-alerts
            send_resolved: true
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
