apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy: {}
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - env:
        - name: GF_SECURITY_CSRF_TRUSTED_ORIGINS
          value: https://grafana.cloudopscenter.es
        - name: GF_SECURITY_CSRF_ADDITIONAL_HEADERS
          value: X-Forwarded-Host
        - name: GF_SERVER_ROOT_URL
          value: https://grafana.cloudopscenter.es/
        image: grafana/grafana:11.3.0
        name: grafana
        ports:
        - containerPort: 3000
        resources: {}
status: {}
