apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: cloud-operations
  source:
    repoURL: quay.io/jetstack/charts
    chart: cert-manager
    targetRevision: v1.21.0
    helm:
      releaseName: cert-manager
      valuesObject:
        crds:
          enabled: true
        global:
          leaderElection:
            namespace: cert-manager
        webhook:
          hostNetwork: true
          securePort: 10260
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
