apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloud-operations
  namespace: argocd
spec:
  description: Cloud Operations Center GitOps project
  sourceRepos:
  - git@github.com:dvdch1258/cloud-operations-center.git
  - https://grafana-community.github.io/helm-charts
  - https://grafana.github.io/helm-charts
  destinations:
  - namespace: cloud-ops
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
